routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::post('/submit', 'HomeController@submitSignature')->name('submit');
Route::get('/signatures', 'SignatureController@index')->name('signatures');
 Route::resource('/signature', 'SignatureController' );

app/Signature.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Signature extends Model
{
      protected $fillable = [

        'signature'

    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use App\Signature;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
       // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
    
    
    public function submitSignature(Request $request)
    {
        $year = date('Y');
        $month = date('m');
        $day = date('d');
        $sub_folder = $year.'/'.$month.'/'.$day.'/';
        $upload_url= 'images/'.$sub_folder;

        if (! File::exists(public_path().'/'.$upload_url)) {
            File::makeDirectory(public_path().'/'.$upload_url,0777,true);
       }

        $signatureName = time() . '.' . "png";  
        $signature = $request->signature;
        $encoded_image = explode(",", $signature)[1];
        $decoded_image = base64_decode($encoded_image);
        Storage::disk("images")->put($sub_folder.$signatureName, $decoded_image);
        
        $signature = new Signature();       
        $signature->signature =  'images/'.$sub_folder.$signatureName;
        $signature->save();
        
        return redirect()->back()->with('success', 'The signature has been saved successfully.');
    }
    
}

app/Http/Controllers/SignatureController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Signature;

class SignatureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $signatures = Signature::orderBy('created_at', 'desc')->paginate(10);
        
         return view('signature.index', ['signatures'=>$signatures]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $signature = Signature::findOrFail($id);
        
         return view('signature.edit', ['signature'=>$signature]);
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $signature = Signature::findOrFail($id);
         
         // delete the old one
         if (is_file(public_path() . $signature->signature)) {

            unlink(public_path() . $signature->signature);
        }
        
        
        $year = date('Y');
        $month = date('m');
        $day = date('d');
        $sub_folder = $year.'/'.$month.'/'.$day.'/';
        $upload_url= 'images/'.$sub_folder;

        if (! File::exists(public_path().'/'.$upload_url)) {
            File::makeDirectory(public_path().'/'.$upload_url,0777,true);
       }

        $signatureName = time() . '.' . "png";  
        $signature_img = $request->signature;
        $encoded_image = explode(",", $signature_img)[1];
        $decoded_image = base64_decode($encoded_image);
        Storage::disk("images")->put($sub_folder.$signatureName, $decoded_image);
         
        $signature->signature =  'images/'.$sub_folder.$signatureName;
        $signature->save();
        
        return redirect()->route('signature.index')->with('success', 'The signature has been updated successfully.');
         
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $signature = Signature::findOrFail($id);
         
         if (is_file(public_path() . $signature->signature)) {

            unlink(public_path() . $signature->signature);
        }
         

         $signature->delete();
         
         return redirect()->back()->with('success', 'The signature has been deleted successfully.');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class=" col-sm-12  col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                   @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <div id="signature-pad" class="signature-pad">
                        <div class="wrapper" id="">
<!--                               <img src="http://www.licensing.biz/cimages/c0f1a3a97bc0de97271f9813f7715bb3.png" width=450 height=350 />-->
                                <canvas id="signature-pad-im"  width=650 height=350  ></canvas>
                        </div>
                        <div class="signature-pad--footer">
                          <div class="description">
                                     <input type='file' id="upload-paper-img" />
                          
                          
                          </div>

                          <div class="signature-pad--actions">
                            <div>
                              <button type="button" id="clear-sg" class="button clear" data-action="clear">Clear</button>                              
<!--                              <button type="button" id="under-sg" class="button" data-action="undo">Undo</button>-->

                            </div>
                            <div>
                                <button type="button" id="save-signature" class="btn btn-primary" >Save </button>
                            </div>
                          </div>
                        </div>
                      </div>
<!--                    <textarea id='output'></textarea><br/>
                     Preview image 
                    <img crossOrigin="Anonymous" src='' id='sign_prev' style='display: none;' />-->
                    <form method="POST" id="myform" action="{{  route('submit') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}        
                        <input type='hidden' id="input_signature" name='signature' value='' />
                    </form>
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/signature_pad.js') }}"></script>    
    <script src="{{ asset('js/script.js') }}"></script>
</head>
<body>
    <div id="app"  class="container-fluid" style="width: 100%">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container-fluid">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        Home
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ route('signature.index') }}">List Signatures</a></li>
                        <!-- Authentication Links -->
                        @guest
                            
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    
</body>
</html>

resources/views/signature/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class=" col-sm-12  col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                   @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <div id="signature-pad" class="signature-pad">
                        <div class="wrapper" id="">
<!--                               <img src="http://www.licensing.biz/cimages/c0f1a3a97bc0de97271f9813f7715bb3.png" width=450 height=350 />-->
                                <canvas id="signature-pad-im"  width=650 height=350  ></canvas>
                        </div>
                        <div class="signature-pad--footer">
                          <div class="description">
                              <img  id="last-signature-img" style="display: none;" src="{{ asset( $signature->signature ) }}">
                          
                          
                          </div>

                          <div class="signature-pad--actions">
                            <div>
                              <button type="button" id="clear-sg" class="button clear" data-action="clear">Clear</button>                              
<!--                              <button type="button" id="under-sg" class="button" data-action="undo">Undo</button>-->

                            </div>
                            <div>
                                <button type="button" id="save-signature" class="btn btn-primary" >Save </button>
                                <a class="btn btn-default" href="{{ route('signature.index') }}">Back</a>
                            </div>
                          </div>
                        </div>
                      </div>
<!--                    <textarea id='output'></textarea><br/>
                     Preview image 
                    <img crossOrigin="Anonymous" src='' id='sign_prev' style='display: none;' />-->
                    <form method="POST" id="myform" action="{{  route('signature.update',$signature->id) }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <input type='hidden' id="input_signature" name='signature' value='' />
                    </form>
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    
    jQuery(document).ready(function () {
        
   
        var canvas = document.getElementById('signature-pad-im');
         var signaturePad = new SignaturePad(document.getElementById('signature-pad-im'), {
			  backgroundColor: 'rgba(255, 255, 255, 0)',
			  penColor: 'rgb(0, 0, 0)'
			});
          context = canvas.getContext('2d');
           signaturePad.clear();
            base_image = new Image();

            base_image.src = $('#last-signature-img').attr('src');
            
        // alert($('#signature-pad-im').width());
          var canvas_width =$('#signature-pad-im').width();
          var canvas_height =$('#signature-pad-im').height();
            base_image.height  =canvas_height  ;
            base_image.width  =  canvas_width;
            //base_image.crossOrigin = "Anonymous";
            base_image.onload = function(){
            //  context.drawImage(base_image, 0, 0,canvas.width,canvas.height);

                    context.drawImage(base_image, 0, 0,canvas_width,canvas_height);
      
            }
         
        
        
    })
    
    
</script>


@endsection

resources/views/signature/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class=" col-sm-12  col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Signatures</div>

                <div class="panel-body">
                   @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                    
                    
                    
                    
                
                     
                         @if($signatures)

                            <div class="row">
                             @foreach($signatures as $signature)
                             
                                
                                                <div class="col-sm-6 col-md-4">
                                                  <div class="thumbnail">
                                                    <a href="#"  data-toggle="modal" data-target="#lightbox"> 
                                                            <img class="img-rounded signature-img-saved"    src="{{$signature->signature ? asset( $signature->signature ): 'http://placehold.it/400x400'}}" alt="Click to view" >
                                                        </a>  
                                                    <div class="caption">
                                                      <h3>Created at : {{$signature->created_at->diffForhumans()}}</h3>
                                                      <p>...</p>
                                                      <p><form method="post" action="{{ route('signature.destroy',$signature->id) }}">
                                                            {{ method_field('DELETE') }}
                                                            <div class="form-group">
                                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                            <input type="submit" class="btn btn-primary" value="Delete"  Onclick="return confirmDelete()"/>

                                                      </form>  <a class="btn btn-success" href="{{ route('signature.edit',$signature->id) }}">Edit</a> </p>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                           
                                    
                            

                             @endforeach
  </div>
                         
                         <div class="row">
                            <div class="col-lg-6 col-sm-offset-5">
                                {{ $signatures->render() }}
                            </div>

                        </div>
                             @endif

                        
                <div id="lightbox" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <button type="button" class="close hidden" data-dismiss="modal" aria-hidden="true">×</button>
                        <div class="modal-content">
                            <div class="modal-body">
                                <img src="" alt="" />
                            </div>
                        </div>
                    </div>
                </div>
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection